# Generated by Django 5.2 on 2025-04-30 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('num_questions', models.PositiveIntegerField()),
                ('content', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('category', models.CharField(choices=[('kanji', 'Kanji'), ('ngu_phap', 'Ngữ pháp'), ('doc_hieu', 'Đọc hiểu'), ('tu_vung', 'Từ vựng'), ('nghe_hieu', 'Nghe hiểu')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('answer_a', models.CharField(max_length=200)),
                ('answer_b', models.CharField(max_length=200)),
                ('answer_c', models.CharField(max_length=200)),
                ('answer_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.test')),
            ],
        ),
    ]
