# Generated by Django 5.2 on 2025-04-30 02:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='content',
        ),
        migrations.RemoveField(
            model_name='test',
            name='num_questions',
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('kanji', 'Kanji'), ('tu_vung', 'Từ vựng'), ('ngu_phap', 'Ngữ pháp'), ('doc_hieu', 'Đọc hiểu'), ('nghe_hieu', 'Nghe hiểu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='level',
            field=models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=10),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
        ),
    ]
