# Generated by Django 5.2 on 2025-05-01 01:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
